### ISSUE TITLE
`num_vars` for bus

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#10]
It would be nice to have the `num_vars` property on a bus level to get the number of variables associated with a specific bus.

**Comment by ttinoco** [comment]
Just the bus or all the elements connected to it as well? This is a bit tricky. If we do this for a bus we should also do it for a generator, battery, branch, etc.

**Comment by martinzellner** [comment]
Maybe both. So a `num_vars` for all direct variables and a function that returns the number of all variables associated with the bus (also generators, batteries, ...)

**Comment by ttinoco** [comment]
This has been implemented in the multi-period branch for all objects but Python wrapper only exposes this for Bus
