### ISSUE TITLE
perform bookkeping of contingency apply/clear inside network components and do not disconnect components

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#125]
otherwise we have a situation that the second line of code of
```
contingency.apply(net1)
contingency.apply(net2)
```
has no effect. 

With regards to disconnecting components: don't disconnect them so that users can still get this info. The downside of this is that then the lower level code will have to have a bunch is "is on outage" if statements. @awig Let's discuss

K-zhuo had issues creating "variable fixing" constraints for Q variables of regulating generators on outage because the constraint construction never gets to them!!!

Progress
- [x] network components
- [x] network properties
- [x] contingencies
- [x] graph
- [x] problem
- [x] constraints
   - [x] ac flow lim
   - [x] ac lin flow lim
   - [x] ac pf
   - [x] bat dyn
   - [x] dc flow lim
   - [x] dc pf
   - [x] fix
   - [x] gen ramp
   - [x] lbound
   - [x] lin pf
   - [x] load pf
   - [x] nbound
   - [x] par gen p
   - [x] pv pq switching
   - [x] reg gen
   - [x] reg shunt
   - [x] reg tran
- [x] functions
   - [x] gen cost
   - [x] load util
   - [x] netcon cost
   - [x] reg phase
   - [x] reg pq
   - [x] reg ratio
   - [x] reg susc
   - [x] reg vang
   - [x] reg var
   - [x] reg vmag
   - [x] slim vmag
   - [x] sp controls
- [x] test utils
- [x] modular func/constr derivative checkers
- [x] existing unittests
- [x] new unittests (test_outages.py)
- [x] apply same contingency to two cases

**Comment by ttinoco** [comment]
done

**Comment by awig** [comment]
amazing job! I was going to take a look at the commits but there are so many! is there anything you want me to review?

**Comment by ttinoco** [comment]
Thanks. I still need to make the constraints/functions robust to users
changing outage flags and not invoking analyze() again. I made that a
separate issue.
I still need to make sure that gridopt/gat work with the new outage
functionality.
