### ISSUE TITLE
Handle zero-impedance branches in PF constraints

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#187]
and avoid need for parsers to merge buses. This will likely require PF constraints to have special linear constraints that enforce the coupling between voltage magnitudes and angles across the branch. This will save the headaches of pfnet networks not having buses/branches present in the input data.

- ACPF
- DCPF
- branch is_zero_impedance
- parsers update

Strategy: create branch P,Q from/to flows as extra variables of ACPF constraints.

**Comment by awig** [comment]
Interesting.  Is there any potential for performance hit with adding these additional constraints in the solvers? Particularly with newton raphson

**Comment by ttinoco** [comment]
no longer need, ZI lines supported in a different way
