### ISSUE TITLE
python-based parsers and autotools

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#21]

**Comment by ttinoco** [comment]
@entriken and @awig : I have created a branch "python-parsers" that allows plugging in parsers written in python to pfnet.
This was done using the Python C API.
The steps for adding a parser are:

1) add a parser written in python to the pfnet.parser submodule
https://github.com/ttinoco/PFNET/tree/python-parsers/python/pfnet/parser
 that is a child class of
https://github.com/ttinoco/PFNET/blob/python-parsers/python/pfnet/parser/parser.py
An example is the DummyPythonParser in
https://github.com/ttinoco/PFNET/blob/python-parsers/python/pfnet/parser/dummy_parser.py

2) add a few lines to [NET_load] (https://github.com/ttinoco/PFNET/blob/python-parsers/src/net/net.c#L1603>)  in [net.c] (https://github.com/ttinoco/PFNET/blob/python-parsers/src/net/net.c) to call the new parser for a specific file type. 
As an example, the code for the DummyPythonParser is
```
else if (strcmp(ext+1,"dummy") == 0) {    
   
    // DUMMY PYTHON
    PYTHON_Parser* parser = PYTHON_PARSER_new("DummyPythonParser");
    PYTHON_PARSER_read(parser,filename);
    #ifdef DEBUG
      PYTHON_PARSER_show(parser);
    #endif
    if (!PYTHON_PARSER_has_error(parser))
      PYTHON_PARSER_load(parser,net);
    if (PYTHON_PARSER_has_error(parser)) {
      strcpy(net->error_string,PYTHON_PARSER_get_error_string(parser));
      net->error_flag = TRUE;
    }
    PYTHON_PARSER_del(parser);
 }
```
This can be simplified a lot since the only thing that depends on the new parser is the class name (e.g. DummyPythonParser)

As an example of usage, loading a network file "foo.dummy" in pfnet gives
```
>>> import pfnet
>>> net = pfnet.Network()
>>> net.load('foo.dummy')
DummyPythonParser created
DummyPythonParser asked to read file foo.dummy
DummyPythonParser asked to load network
Network received by DummyPythonParser is of type <type 'pfnet.cpfnet.Network'>
DummyPythonParser destroyed
```
which shows that the new parser can be used in the same was as the parsers written in C, and that the new parser receives a python pfnet network object. 

The python parser gets an empty pfnet Network and needs to construct it and fill it in with the parsed data. 
For this to be possible, many or all the low level routines of pfnet need to be exposed in the python wrapper. Some help with this would be nice. One can look at the [MAT] (https://github.com/ttinoco/PFNET/blob/python-parsers/src/parser/parser_MAT.c#L239) or [ART] (https://github.com/ttinoco/PFNET/blob/python-parsers/src/parser/parser_ART.c#L491) parsers to see what routines are used to construct and fill the network. 

The Makefile needs a few modifications, as shown in
https://github.com/ttinoco/PFNET/blob/python-parsers/Makefile
The changes shown are specific to my system and need to be updated to be usable by a generic user.

@martinzellner : we can start discussing integrating your CIM parser

**Comment by ttinoco** [comment]
Notes about python parser and autotools
1. python-based parsers work with autotools
2. autotools automatically checks availability/requirements of raw parser, graphviz and python-based parsers
3. for C library, need to do configure, make, make check, make install 
4. python wrapper only needs to find libpfnet. User no longer needs to pass --no_raw_parser, no_graphviz, etc.  User is responsible for making libpfnet visible to linker (I point LD_LIBRARY_PATH to /usr/local/lib). 
5. to build libpfnet with python-based parsers, configure needs to detect availability of cpfnet.so, hence one may need to do a double build: configure, make, make install, build python wrapper inplace, then configure make make install again for libpfnet to automatically include python-based parser functionality
6. pfnet python package now has "info" attribute that shows the availability of raw parser, graphviz, python-based parsers (this seems pretty cool):
7. unittests were added to check that python-based parsers work, and that the package "info" attribute is ok.
8. this commit works with raw_parser from the autotools-tomas branch, it requires RAW_PARSER env variable to detect if libraw_parser.so is available
```
>>> import pfnet
>>> pfnet.info
{'python parsers': True, 'raw parser': True, 'graphviz': True}
```

**Comment by ttinoco** [comment]
@awig  please have a look at the "notes about python parsers and autotools" and let me know what you think. I think we can move forward after you approve and merge into dev. Merging will be easy since this branch (autotools-tomas) already has the latest dev features incorporated (extra variables in constraints, ac thermal limits, etc)

**Comment by ttinoco** [comment]
completed

**Comment by awig** [comment]
@ttinoco 

Sorry for not getting to this until now. My responses are in **Bold**

Notes about python parser and autotools (autotoots-tomas branch)

    python-based parsers work with autotools
    autotools automatically checks availability/requirements of raw parser, graphviz and python-based parsers -- **awesome!**
    for C library, need to do configure, make, make check, make install **i'll test on mac and ubuntu**
    python wrapper only needs to find libpfnet. User no longer needs to pass --no_raw_parser, --no_graphviz, etc. User is responsible for making libpfnet visible to linker (I point LD_LIBRARY_PATH to /usr/local/lib).  **we could also add to the documentation how to run make while adding to and LDFLAG for exmaple: ``make -LDFLAG+=/path/to/libpfnet.so``**
    to build libpfnet with python-based parsers, configure needs to detect availability of cpfnet.so, hence one may need to do a double build: configure, make, make install, build python wrapper inplace, then configure make make install again for libpfnet to automatically include python-based parser functionality ("double build") **I think I already had to do this, we'll have to strange our builder scripts, let's just make sure it is documented well**
    pfnet python package now has "info" attribute that shows the availability of raw parser, graphviz, python-based parsers (this seems pretty cool): **nice!**
    unittests were added to check that python-based parsers work, and that the package "info" attribute is ok.
    this commit works with raw_parser from the autotools-tomas branch, it requires RAW_PARSER env variable to detect if libraw_parser.so is available  **hmm, so it won't automatically check the lib folder in PFNET? I wonder if we could just have a default raw-parser folder in PFNET that is automatically checked if you install raw-parser there? adding a new env is okay but not my first inclination.**
    documentation is generated by typing "make html" in each of the "docs" directories (c, python, matlab). All require PFNET_DOCS to be defined. **awesome!**

** I need to test this all out. Sorry it is taking so long.**

>>> import pfnet
>>> pfnet.info
{'python parsers': True, 'raw parser': True, 'graphviz': True}

**Comment by ttinoco** [comment]
@awig 
thanks for the comments. 
* I added travis continuous integration and am automatically testing autotools-pfnet in osx and and linux. 
https://travis-ci.org/ttinoco/PFNET (have a look at the .travis.yml file)
* I managed to get the python wrapper working without the need of LD_LIBRARY_FLAGS in both linux and osx (again, have a look at .travis.yml). I am using -rpath /usr/local/lib and also allow an optional --libdirs argument that specifies both library locations a that go into -L and -rpath, which I am using for readthedocs (see below).
https://github.com/ttinoco/PFNET/blob/master/python/setup.py
* I really like your idea about a raw_parser folder or something similar. I agree with you about avoiding env variables.  Right now I am using the raw_parser from the autotools-tomas branch.
* Since autotools was tested on osx and linux, and since I already updated the C and python documentation for this branch (on readthedocs!!!), I went ahead and merged all these changes to dev and master and created a pre-release (1.2.8). I decided to do this since it was too much work to get readthedocs working for the branches with and without autotools (it is pretty tricky to build C dependencies in order to load the cython extension module and get sphinx to "observe" the module). The documentation in readthedocs is up-to-date so there you can see the updated installation instructions for both C and python, which are much simpler now. Have a look at the README file, they have some cool badges now that are linked to the status of the docs and of travis-ci. From now on it will be very easy to keep documentations for all the subsequent releases. I am no longer using gh-pages in github and hence I removed this branch
