### ISSUE TITLE
Import fails on multi_period branch

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#29]
The import of PFNET currently fails on the [multi_period branch](/ttinoco/PFNET/tree/multi_period):
```
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/pfnet/cpfnet.cpython-35m-darwin.so, 2): Symbol not found: _BAT_get_E_final
  Referenced from: /usr/local/lib/python3.5/site-packages/pfnet/cpfnet.cpython-35m-darwin.so
  Expected in: /Users/murphy/git/PFNET/lib/libpfnet.so
 in /usr/local/lib/python3.5/site-packages/pfnet/cpfnet.cpython-35m-darwin.so
```

**Comment by ttinoco** [comment]
For me it works. Maybe you are linking to the old library?

**Comment by martinzellner** [comment]
Weird. It seems to matter whether you are in module directory of PFNET when you execute the import.
Never mind, it works now.

**Comment by ttinoco** [comment]
Yes, it matters. When importing pfnet in the pfnet/python directory python the local package has precedence over the system pacakage and the local package does not have the cython stuff built in-place. You should do "python setup.py build_ext --inplace"

**Comment by martinzellner** [comment]
Makes sense. Obviously I got lucky a couple of times.
Maybe we should change that in the [documentation](http://ttinoco.github.io/PFNET/python/start.html#installation).

**Comment by ttinoco** [comment]
It says in the docs to use build_ext already. Do you have something else in mind? It would be better I think to have the "install" command also build inplace.

**Comment by martinzellner** [comment]
I think it would be good to also use build inplace here:
<img width="1272" alt="screen shot 2016-08-29 at 15 58 48" src="https://cloud.githubusercontent.com/assets/855054/18053828/94d3ab26-6e01-11e6-9024-e0cd3f45bba9.png">

**Comment by ttinoco** [comment]
Ok I see. However, maybe is better to incorporate this build inplace in the install command, to save users some trouble. Having to do two commands is also a bit annoying during development
