### ISSUE TITLE
portability problem: windows line endings in .mat files

### ISSUE THREAD

**Issue by nwh** [ttinoco/PFNET#31]
We have been working on a windows distribution for PFNET.  It turned out that git was automatically translating unix line endings (LF) to windows line endings (CRLF) in checkout.  (Windows git will automatically translate back upon a commit)

This causes the C-based tests to fail on the .mat files included with PFNET source code when checked out from git.

It might be good to check data files for windows line endings and error out on load/parse if they are present.

@awig

**Comment by awig** [comment]
I will work on this in romcon. This is probably very useful for the EPRI package.

**Comment by ttinoco** [comment]
Done
