### ISSUE TITLE
Batteries are not shown by `show_components()`

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#4]

**Comment by ttinoco** [comment]
They are. Did you try the case32.art file or are you adding batteries to another file? If you are adding batteries then make sure the records in the file end with ;
![screenshot from 2016-05-05 18 14 41](https://cloud.githubusercontent.com/assets/6379647/15049155/55c16d7a-12ed-11e6-86ac-2e5e4203351f.png)

**Comment by martinzellner** [comment]
Oh, sorry. I was executing the `show_components()`of mppfnet and got confused...
