### ISSUE TITLE
Pythonic Bus Sensitivities and Mismatches

### ISSUE THREAD

**Issue by awig** [ttinoco/PFNET#40]
To complete the pythonic transition from C integer masks, we need to convert the Bus Sensitivities and Bus Power Mismatches to strings.

See,
http://ttinoco.github.io/PFNET/python/reference.html#bus-sensitivities
http://ttinoco.github.io/PFNET/python/reference.html#bus-power-mismatches

**Comment by ttinoco** [comment]
done on master
