### ISSUE TITLE
active distribution grid mutliperiod ACOPF

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#56]
### variables
- [x] generator powers (P,Q)
- [x] bus voltage magnitude and angles
- [x] load powers (P,Q)
- [x] renewable powers (P,Q) and curtailment support
- [x] battery charging powers and energy levels
- [x] transformer tap ratios

### objectives
- [x] generation cost
- [ ] renewable curtailment cost
- [ ] smooth gen Q profiles

### constraints
- [x] generator ramping
- [x] renewable PQ capability (square for now)
- [x] battery dynamics (check handling of efficiencies)
- [x] battery boundary conditions
- [x] AC PF and net properties (with battery, variable generator, and load support)
- [x] AC branch flow limits
- [x] voltage magnitude limits, device limits (gens,loads, renewables, batteries, transformers)
- [x] load constant power factor

### misc
- [x] handling of renewable powers curtailment
- [x] user-friendly addition of batteries and renewable energy sources to network

**Comment by awig** [comment]
This is very helpful.  We could also link these to modeling capabilities to be added, for instance FACTS or other power flow control devices, HVDC, voltage-dependent or complex loads, so we know what is needed to model what new network components. What do you think?

Shouldn't limiting control actions be included in constraints?

Here are a couple of other thoughts to consider

to variables:
- voltages as polar coordinates ?
- what would be needed for power flow controls such as FACTS ?

to objectives:
- minimize network losses
- minimize transfers (over specific corridors)
- maximize reactive power capability and hence voltage stability security ? 

to constraints:
- voltage dependency of loads
- voltage stability limits (not sure on the formulation, need to ask Bob)
- polar coordinate voltage limits ?

**Comment by ttinoco** [comment]
Sounds good.  For limiting control actions we still have the sparsity-inducing penalty. 
I think you mean rectangular coordinates. Great idea. I would suggest moving this list of items to another more general issue called "new variables, functions and constraints". The items you have listed here are great. I will then add to that list things like: generator commitment variables, minimum up-down constraints, generator start-up costs, etc (for unit commitment).

**Comment by ttinoco** [comment]
done
