### ISSUE TITLE
FIX constraints are not working as expected for Loads

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#6]
I am experiencing problems when setting the load variables as fixed. The number of fixed variables increases, however the `A` matrix seems unchanged.

Looking at https://github.com/ttinoco/PFNET/blob/master/src/problem/constr/constr_FIX.c it seems like the FIX constraint is not implemented for loads. Is this the case or am I doing something wrong?

**Comment by ttinoco** [comment]
I will check this today in a few hours.

**Comment by ttinoco** [comment]
I just added this and pushed to master. I added unittests but do some sanity checks of your own.

**Comment by martinzellner** [comment]
Cool, thanks!

**Comment by ttinoco** [comment]
No problem. Just close this issue after you see it working well in your code.

**Comment by martinzellner** [comment]
The load constraints work now as expected. Thanks!
