### ISSUE TITLE
Use existing commands of build_ext instead of adding the redundant incdir, libdir, libpfnet with argparse

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET#66]
python setup.py currently defines new arguments --libdirs --incdirs and --libpfnet using argparse. This is silly because build_ext already has these comments. 

These extra commands were first introduced to do a custom build for getting readthedocs to work. See python/docs/build.sh

**Comment by ttinoco** [comment]
@awig I will take care of this while processing the PR. I will provide a setup.cfg with default include dirs, libdirs and libraries (-lpfnet), and anyone can just change these or overwrite them by passing aguments to build_ext (they already exist, we don't need argparse)

**Comment by ttinoco** [comment]
@awig This has been done. Please have a look at 
https://github.com/ttinoco/PFNET/blob/master/python/setup.py (pretty clean right?)
https://github.com/ttinoco/PFNET/blob/master/python/setup.cfg
and
https://github.com/ttinoco/PFNET/blob/master/python/docs/build.sh
This last script shows you an example of how to do a custom build by passing arguments to build_ext and overwriting the values specified in setup.cfg. I am using this for readthedocs but you can use this as an example for your custom build. You can also pass --libraries=xxxx if your pfnet library has another name.

**Comment by awig** [comment]
@ttinoco nice. very clean. I'm not familiar with setup.cfg as part of distutils but after some quick searching I agree it is the better approach and is also supported in setuptools.

I need to test the latest build and merge it back into romcon soon. I'll let you know if I run into an problems when building cross platform (Windows), but that is unlikely.
