### ISSUE TITLE
Provide net consumption of bus as variable

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#7]
It would be nice to be able to define a net_cost variable (say `z`) for each bus. With an `index_z` it would be convenient to refer to that variable of the optimization problem.

**Comment by ttinoco** [comment]
I have to think about this since it has implications on constraints. If we introduce z then we may need an implicit constraint that makes z a function of other variables. I have been thinking of a similar issue that arises if we define variables that represent branch active and reactive flows.
