### ISSUE TITLE
Projection of constraints for a certain area

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/PFNET#8]
As discussed in the meeting, it would be nice to have a projection that returns the `A` matrix of constraints in a certain area (one or multiple buses).

**Comment by ttinoco** [comment]
We discussed having a projection matrix that projects the vector x of all variables to the ones that are associated with a bus or with a region. I think it makes sense to use a new "area" attribute of buses. Right now one can project to variables of a specific object (e.g. bus) and type (e.g. voltage magnitude). I need to make this routine much more general.
