### ISSUE TITLE
New AX check compile flags breaks autotools build on OSX

### ISSUE THREAD

**Issue by awig** [ttinoco/PFNET#91]
The new "chew flags" breaks on OSX using autotools with the following error:

```
./configure: line 12805: syntax error near unexpected token `-Wall,'
./configure: line 12805: `AX_CHECK_COMPILE_FLAG(-Wall, CFLAGS="$CFLAGS -Wall", , )'
```

**Comment by ttinoco** [comment]
Yes, I am aware. You need brew install autoconf-archive (I added some
comment about this in the docs). I do not like the dependency but the check
is nice

**Comment by ttinoco** [comment]
See the file .travis.ylm , it tests osx

**Comment by awig** [comment]
Ok. Thanks I didn't see that added there.  Works now. Closing.
